
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        
    )

    (:init
        (= (total-cost ) 0)
        (on_e_b )
        (on_d_e )
        (ontable_c )
        (clear_e )
        (clear_a )
        (holding_d )
        (ontable_a )
        (on_b_c )
    )

    (:goal
        (on_d_e )
    )

    
    
    (:metric minimize (total-cost ))
)

