
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        
    )

    (:init
        (= (total-cost ) 0)
        (clear_c )
        (on_d_b )
        (ontable_c )
        (on_b_a )
        (ontable_a )
        (handempty )
        (clear_d )
    )

    (:goal
        (and (on_d_c ) (on_b_d ))
    )

    
    
    (:metric minimize (total-cost ))
)

