
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance1)
    (:domain test_domain)

    (:objects
        
    )

    (:init
        (= (total-cost ) 0)
        (clear_c )
        (on_c_a )
        (ontable_d )
        (clear_d )
        (ontable_b )
        (on_a_b )
        (handempty )
    )

    (:goal
        (on_c_a )
    )

    
    (:bounds
        (number - int[-2147483647..2147483647]))
    (:metric minimize (total-cost ))
)

